### ISSUE TITLE
Volumes are no longer mounted now

### ISSUE THREAD

**Issue by Swizz** [signalfx/maestro-ng#103]
Hi

Since I updated docker yesterday no volume are mounted when I start instance.
No `maestro.yml` have been changed.

An exemple of one of these :

```
name: swizz540.github.io

registries:

ships:
  localhost:
    ip: 127.0.0.1
    docker_port: 4243

services:
  jekyll:
    image: grahamc/jekyll:latest

    instances:
      swizz.github.io:
        command: "serve -w"
        ship: localhost
        ports: {http: 4000}
        volumes:
          /src: /home/swizz/Works/swizz540.github.io
```

I use maestro-ng everyday. And I try for all my project. No one works as it should.

Thanks for support,
Kind regards.
