### ISSUE TITLE
Start hangs at "waiting for service..." when external port is bound to 127.0.0.1

### ISSUE THREAD

**Issue by corradio** [signalfx/maestro-ng#12]
Hello,

This is my config.yaml:

``` yaml
ports: 
    mongod: 
        exposed: 27017
        external: [ 127.0.0.1, 27017 ]
```

When external port is 127.0.0.1, maestro can't ping to check that the port is up, thus causing a timeout at status 'waiting for service...'
