### ISSUE TITLE
Maestro does not allow exposing ports with protocols other than TCP

### ISSUE THREAD

**Issue by jpfuentes2** [signalfx/maestro-ng#2]
[Here](https://github.com/signalfuse/maestro-ng/blob/master/maestro/entities.py#L193-L206) and [here](https://github.com/signalfuse/maestro-ng/blob/master/maestro/plays.py#L250) means I cannot expose a port using UDP.

I suggest adding the ability to parse out:

``` yaml
instances:
  riemann:
    ports:
      server: "5555/udp"
```
