### ISSUE TITLE
TCP lifecycle check does not work

### ISSUE THREAD

**Issue by NicolasTr** [signalfx/maestro-ng#53]
The lifecycle check didn't work properly with the following configuration file:

```
name: test
ships:
    master: {ip: &master_ship_ip localhost, docker_port: 4243}
services:
    postgres:
        image: postgres
        instances:
            postgres-1:
                ship: master
                ports: {test: 9998}
                lifecycle:
                    running: [{type: tcp, port: test}]
```

I expect maestro-ng to tell me that the container did not start because the port is closed.

I think the problem comes from [here](https://github.com/signalfuse/maestro-ng/blob/1291238d0cee35521dd4fa68378df9e3f15899d1/maestro/lifecycle.py#L42-L45). The port 9998  on the host machine redirects to the same port on the container. Python sees that port as open on the host machine even if the port is closed on the container.

$ docker ps

```
CONTAINER ID        IMAGE                                 COMMAND                CREATED             STATUS              PORTS                                       NAMES
c9a7978fce19        postgres:latest                       /usr/src/postgres/do   2 minutes ago       Up 2 minutes        5432/tcp, 0.0.0.0:9998->9998/tcp            postgres-1
```

$ maestro -v

```
maestro-0.1.8.2
```

$ docker version

```
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
Server version: 1.0.1
Server API version: 1.12
Go version (server): go1.2.1
Git commit (server): 990021a

```
