### ISSUE TITLE
Restart policy not working?

### ISSUE THREAD

**Issue by lolski** [signalfx/maestro-ng#95]
Setting restart policy to `always` with `maximum_retry_count: n` seem to have no effect, proven upon doing a `docker inspect mycontainer`:

``` json
"RestartPolicy": {
    "MaximumRetryCount": 0,
    "Name": ""
},
```

Here's an excerpt from my `maestro.yaml`

``` yaml
mycontainer:
  image: image
  requires: [ req1, req2, req3 ]
  instances:
    mycontainer:
      ship: host
      links:
        req1: req1
        req2: req2
        req3: req3
      restart:
        name: always
        maximum_retry_count: 5
```

Can anyone confirm this?
